#Serviced by /gaussian_process/start_process
#REQ cloud: full path  to object pcd file to use, if empty
#calls pacman_vision get_cloud_in_hand service to get point cloud from vision.
string obj_pcd
---
shape_msgs/Mesh predicted_shape